// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZmVZSD-hKdn7pTEg5EHCuaYEo3b2OkIw',
    appId: '1:445247952089:web:03235477950829e4109ac8',
    messagingSenderId: '445247952089',
    projectId: 'handyapp-f6206',
    authDomain: 'handyapp-f6206.firebaseapp.com',
    databaseURL: 'https://handyapp-f6206.firebaseio.com',
    storageBucket: 'handyapp-f6206.appspot.com',
    measurementId: 'G-F39LEQNKDK',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw4VHq4fBhQ_vTIdewYfRY1kmYH51MOfk',
    appId: '1:445247952089:ios:e06f52396e97c628109ac8',
    messagingSenderId: '445247952089',
    projectId: 'handyapp-f6206',
    databaseURL: 'https://handyapp-f6206.firebaseio.com',
    storageBucket: 'handyapp-f6206.appspot.com',
    iosClientId: '445247952089-59paq57koide234j22mhbr6rsoo26fpg.apps.googleusercontent.com',
    iosBundleId: 'edu.osu.handdx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw4VHq4fBhQ_vTIdewYfRY1kmYH51MOfk',
    appId: '1:445247952089:ios:e06f52396e97c628109ac8',
    messagingSenderId: '445247952089',
    projectId: 'handyapp-f6206',
    databaseURL: 'https://handyapp-f6206.firebaseio.com',
    storageBucket: 'handyapp-f6206.appspot.com',
    iosClientId: '445247952089-59paq57koide234j22mhbr6rsoo26fpg.apps.googleusercontent.com',
    iosBundleId: 'edu.osu.handdx',
  );
}
